{% set version = "0.2" %}
{% set required_compiler_and_mkl_version = "2024.0" %}
{% set excluded_compiler_version1 = "2024.0.1" %}
{% set excluded_compiler_version2 = "2024.0.2" %}

package:
  name: sharpy
  version: {{version}}

source:
    git_url:  ../

requirements:
  host:
    - pip
    - python
    - cmake >=3.26
    - git
    - setuptools
    - numpy x.x
    - pybind11
    - ninja
    - tbb-devel
    - impi-devel
    - mpi4py
    - wheel
    - libzlib
    - xz <=5.4.6  # CVE-2024-3094

  build:
    - {{compiler('gxx')}} <=12.3.0
    - sysroot_linux-64  # [linux]
#    - sysroot_linux-64 >=2.28  # [linux]
    - dpcpp_linux-64 >=2024.1 # [linux]
    - dpcpp_win-64  # [win]
    # - {{compiler('dpcpp')}} >={{required_compiler_and_mkl_version}},!={{excluded_compiler_version1}},!={{excluded_compiler_version2}} # [not osx]
  run:
    - numpy x.x
    - tbb
    - impi_rt
    - mpi4py
    - sysroot_linux-64 >=2.28  # [linux]

build:
  number: 0
  script_env:
    - GITHUB_WORKSPACE

test:
  # requires:
  #   - pytest
  script_env:
    - GITHUB_WORKSPACE
  imports:
    - sharpy

about:
  home: http://github.com/IntelPython/sharpy
  license: BSD-3-Clause
  license_file: ../LICENSE
  summary: Distributed Array for Python on CPU and GPU
  description: |
    <strong>This software package is not ready for production use and
    and merely a proof of concept implementation.</strong>
    <br/><br/>
    <strong>LEGAL NOTICE: Use of this software package is subject to the
    software license agreement (as set forth above, in the license section of
    the installed Conda package and/or the README file) and all notices,
    disclaimers or license terms for third party or open source software
    included in or with the software.</strong>
    <br/><br/>
    EULA: <a href="https://opensource.org/licenses/BSD-3-Clause" target="_blank">BSD-3-Clause</a>
    <br/><br/>
